<?php
/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_help().
 */
function sociallinks_help($path, $arg) {
  switch ($path) {
    case 'admin/help#sociallinks':
      $output = '';
      $output .= '<p>' . t('Social links') . '</p>';
      return $output;
  }
}

/**
 * Social links in header of page.
 *
 * @return
 *   HTML output.
 */
function sociallinks_header_bar() {
  $output = '';

  $menu_links = array();

  $menu_links[] = array(
    'href' =>  'https://www.facebook.com/drupalcampwroclawpl',
    'title' => t('Facebook'),
    'attributes' => array('class' => 'facebook', 'target' => '_blank'),
  );
  $menu_links[] = array(
    'href' =>  'https://twitter.com/drupalcamp_wroc',
    'title' => t('Twitter'),
    'attributes' => array('class' => 'twitter', 'target' => '_blank'),
  );
  $menu_links[] = array(
    'href' =>  'https://plus.google.com/+DrupalcampwroclawPl',
    'title' => t('Google Plus'),
    'attributes' => array('class' => 'gplus', 'target' => '_blank'),
  );
  $menu_links[] = array(
    'href' =>  'rss.xml',
    'title' => t('RSS'),
    'attributes' => array('class' => 'rss', 'target' => '_blank'),
  );

  $output .= theme('links',  array(
                'links' => $menu_links,
                'attributes' => array('class' => array('social-links'))));

  return $output;
}
